# -*- MakeFile -*-
BINARY = project1
SRCFILES = project1.c\
	hal_low/gpio_setup/gpio_init.c\
	low_level_app/gpio_low_level_app/gpio_start.c\
	hal_low/adc_setup/adc_init.c\
	low_level_app/adc_low_level_app/adc_start.c\
	hal_low/uart_setup/uart_init.c\
	low_level_app/uart_low_level_app/uart_start.c\
	hal_low/tim_setup/tim_init.c\
	low_level_app/tim_low_level_app/tim_start.c\
	hal_low/tim3_setup/tim3_init.c\
	low_level_app/tim3_low_level_app/tim3_start.c\
	low_level_app/isr_low_level_app/isr_start.c

all: elf bin

include ../Makefile.incl

 
